### ISSUE TITLE
Add test for sqlite nuspec 

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware#240]
## Background

When building the nuget package for sqlite the `.nuspec` file needs to configured correctly.

When adding a new package and it is forgotten to update the `.nuspec` file the released package can not be used in a `PackageReference` which is needed for the Android Launcher and SignatureCloud.DE.

## Solution

Create a smoketest thats running in CI which packs and publishes the SQLite queue to a local directory nuget repository and then tries to use this package from the repository.

## Tasks

- [x] Reproduce locally in android launcher repository (using SQLite version 1.3.53)
- [x] Reproduce in android launcher with a local nuget repository where we publish an intentionally broken package to (break the package by e.g. removing the `QueueDEFAULT` from the `queue/src/fiskaltrust.Middleware.Queue.SQLite/.nuspec`)
- [x] Reproduce in new test project in the middleware repository
- [x] Add to test to `fiskaltrust.Middleware.Queue` pipeline that fails if the package is broken
     - [x] Add a new project that resembles the Android launcher project 
     - [x] Create a local feed on the pipeline that contains Queue.Sqlite package
     - [x] Add pipeline tasks to build a new project
     - [x] Force the project to use the Queue.Sqlite package from local feed
