### ISSUE TITLE
Update FCC to 4.0.8 in SwissbitCloud and DF SCUs

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/middleware#249]
## Background
The DeutscheFiskal released several new versions since our last update (we're on version 4.0.5, latest is 4.0.8. Most of the changes ([listed here](https://documentation.fiskal.cloud/md/changelog/changelog)) are not _super_ relevant for us, but a breaking change was introduced in 4.0.8 and our MW is not compatible with this version anymore.

## Problem
A breaking change was introduced in FCC 4.0.8: the `GET /info` and `POST /registration` endpoints now require authentication. While we already have that in place for the latter, we use the `/info` endpoint without auth, leading to a failing `GetTseInfo()` method.

## Solution
We need add authentication to the `info` endpoint, and should update our internally used FCC to v4.0.8. 
Additionally, we need to verify that the `info` endpoint of old FCCs can be used with authentication as well, in case someone wants to use older versions.

## Tasks
- [ ] Add admin authentication to the client calling the `info` endpoint
- [ ] Ensure that other endpoints (i.e. `/registration`) are correctly authenticated
- [ ] Test if these changes still work with FCCs older than 4.0.8 (easiest by doing this before updating to 4.0.8)
- [ ] Update the default used FCC version to 4.0.8
- [ ] Upload the FCC packages to our download storage
- [ ] Release the `DeutscheFiskal` and `SwissbitCloud` SCUs v.1.3.55 (or 56?)
- [ ] Write release notes
