### ISSUE TITLE
FCC 4.0.8: Include metrics option

### ISSUE THREAD

**Issue by saschaknapp** [fiskaltrust/middleware#256]
Background:
It's possible to set up a monitoring environment for the Fiscal-Cloud-Connector. The FCC creates metrics that are then fetched by monitoring solutions like prometheus and can be visualized in grafana. The metrics need to be activated in the FCC. We have at least one customer who wants to set up FCC monitoring.

HowTo activate:
There are two options to activate the metrics:

- At the time of installation/initialization of the FCC: For this the parameter "enable-components metrics" is available
![image](https://github.com/fiskaltrust/middleware/assets/47039335/5c4bf716-ffaf-4b27-9105-49663530c1d1)

- After the FCC installation/initialization the metrics can be activated by adding the following parameter to the run_fcc.bat -Dspring.profiles.active=metrics

It should be possible to activate the metrics in the scu configuration.

HowTo test:
You can test if the metrics work without having to set up prometheus by opening the following URL in your browser. If data is shown there, then the metrics are active:
localhost:20001/actuator/metrics/http.server.requests
Port can be different if a individual fccPort was configured

More info:
https://documentation.fiskal.cloud/md/fiskal_cloud_connector/fiskal_cloud_connector/#metrics
https://documentation.fiskal.cloud/md/fiskal_cloud_connector/fiskal_cloud_connector/#list-of-installer-parameters-for-unattended-mode

## Tasks
- [x] Add boolean SCU parameter `EnableFccMetrics` to DeutscheFiskal and SwissbitCloud SCUs
- [x] If the SCU parameter is set to `true`, add `Dspring.profiles.active=metrics` parameter when starting the FCC
- [x] Update SCU parameter documentation on docs.fiskaltrust.cloud
- [x] Test if metrics are generated (as described above)

**Comment by saschaknapp** [comment]
as discussed @TSchmiedlechner :)
