### ISSUE TITLE
Update FCC to 4.1.1 and release SwissbitCloud and DF SCUs

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/middleware#272]
## Problem
The DeutscheFiskal has released an update to their FCC that is mandatory to install until end of July because of a certificate update.

## Solution
We need to update our reference to the FCC to v4.1.1, and release the two affected SCUs as version 1.3.56.

## Tasks
- [x] Update FCC version to 4.1.1 in SwissbitCloud and DeutscheFiskal SCUs
- [x] Upload the zip files to the download storage
- [x] Test on sandbox
    - [x] New installation
    - [x] Update from previous version
- [x] Release
   - [x] DeutscheFiskal SCU v1.3.56
   - [x] SwissbitCloud SCU v1.3.56
   - [x] Write release notes
- [x] Inform @saschaknapp and @marcoleidl about the release, so that we can inform our customers that this update is mandatory
