### ISSUE TITLE
Support creation of X-Reports for Epson RT Printer

### ISSUE THREAD

**Issue by StefanKert** [fiskaltrust/middleware#298]
Epson RT Printers support printing a so called `X-01 financial report`. This report is used in various different business processes and therefore is necessary to be available via the Middleware.

While the need of this report is clear, retrieving all the necessary data for this report is usually a feature that would be covered by the Middleware (e.g. via a specific Journal endpoint) or a Portal export. Even though we will recommend integrators to use one of these capabilities to get the financial data or probably an export that is generated by their POS, some processes still require the actual printed document. 

To support getting the printed documents we will add an additional `local ftReceiptCaseFlag` (_4954_2**III**_0000_0000). This flag is only supported with a given set of SCUs and will not be part of the main interface. 

**This flag is specific to Italy and will have a different functionality in other Markets.**

The following defaults should be taken in consideration in documentation and implementation 
- If the SCU that is connected does not support printing X-Reports the flag will be ignored. This allows us to easily switch between SCUs and still give integrators flexibility on integration
- Official recommendation is using either reports from your POS or the once we provide in portal. Since we consider the RT Printers being only a Signature Device, printing the receipt via it is just a workaround. POS Systems do usually give a clearer picture and can handle more of the cases in a better way than the printer so this should give end-users better visibility. 
- The flag will be supported in the *Zero Receipt only* (0x4954_2000_0000_2000) . Since this is a very specific action that will be called on demand it is a very similar process as we are using now in DE for some receipts.
- The flag is only evaluated in the SCU. The Queue will just pass-through the zero receipt and mustn't change behavior 

Since the local flags don't follow a specific logic and just need to be additive we will start with 001

0x4954_2001_0000_2000

### ToDos

- [x] Extend Epson RT Printer SCU to support X Report Flag
- [ ] Extend Custom RT Printer SCU to support X Report Flag
- [ ] Extend Documentation with new local ReceiptCaseFlag

**Comment by StefanKert** [comment]
@FrancescoMataloniFiskaltrust can you probably check the documentation part? I am not sure if it makes sense to also create a KBA for that. One thing that we should mention in any documentation is that this behavior is specific to the RT device that is being used and will not work with some of them.

**Comment by FrancescoMataloniFiskaltrust** [comment]
@StefanKert added in the documentation (see PR: https://github.com/fiskaltrust/interface-doc/pull/327)

**Comment by StefanKert** [comment]
Finished and rolled out
