### ISSUE TITLE
Re-add support for FCC 32-bit to DeutscheFiskal SCU

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/middleware#303]
# Problem
Initially, the FCC did not support 32-bit Windows environments anymore, because it wasn't certified by the BSI. This was now changed

# Solution
We should re-enable the FCC download for 32-bit OS; i.e. removing the respective check from `GetDownloadUriByCurrentPlatform()`.

# Tasks
- [x] Don't throw an exception in `GetDownloadUriByCurrentPlatform()` when the OS is 32-bit
- [x] Upload the FCC 4.1.1 for 32-bit Windows to our download storage
- [x] Release a new version of..
   - [x] DeutscheFiskal SCU
   - [x] SwissbitCloud SCU
   - [x] Write release notes
