### ISSUE TITLE
Daily Closing Numbers do not include Closings Without ActionJournal

### ISSUE THREAD

**Issue by forsthug** [fiskaltrust/middleware#322]
Before 2012-03-10 no ActionJournal was written for Closings. Those are missing when calculating the number 

![Image](https://github.com/fiskaltrust/middleware/assets/85173816/0c696d58-33ba-4f3a-b968-29c8f4805457)

Change here and check for json null
https://github.com/fiskaltrust/middleware/blob/main/queue/src/fiskaltrust.Middleware.Localization.QueueDE/Repositories/DailyClosingRepository.cs#L36

After adding the cached queueitems its possible to calculate in datapipes receipt reference downloader
https://fiskaltrust.visualstudio.com/fiskaltrust/_git/fiskaltrust.DataPipes?path=/src/Tasks/fiskaltrust.DataPipes.ReceiptReferenceDownloader/Downloader.cs&version=GBmain&line=61&lineEnd=62&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

Check for same numbers local and in  datapipes.

## Tasks
- [x] Don't throw exceptions if the closingNumber property in the actionJournals related to daily closings is not set
- [x] If the value is not set, read the dailyclosingNumber from the ftStateData property of the connected receipt's response
- [x] Test (e.g. by removing the `dailyclosingnumber` in an actionJournal)
