### ISSUE TITLE
Add Middleware version to QueueItem entity

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/middleware#361]
# Context
Currently, we cannot know in retrospective which version of the Middleware processed a QueueItem. Knowing this would be very practical though, e.g. in reports and also to make specific features (for example in exports) based on this version.

# Solution
We will add a new field to the `ftQueueItem` entity, both in the Middleware's local storages as well as in our Azure storage. The field will be set to the full version of the current Middleware, e.g. `1.3.45` or `1.3.45-rc1-123123-12312321`.

## Tasks
- [x] Add a new nullable string field `ProcessingVersion` to  `ftQueueItem` entity in the `fiskaltrust.storage` package
- [x] Add the updated package to the Middleware and update the Storage implementations **and the migrations**
   - [x] SQLite
   - [x] Azure Storage
   - [x] MySQL
   - [x] EF
   - [x] PostgreSQL
- [x] Update the package in Helipad and write the incoming fields to the account storage.
   - [x] Ensure that the field is nullable and old MW versions that don't send the field can still upload
   - [x] End2End test (i.e. create receipts and verify them in the storage)
- [x] Test with..
   - [x] Launcher 1.3
   - [x] Launcher 2.0
   - [ ] Android
   - [x] BYODC/CloudCashbox

**Comment by volllly** [comment]
Do we also want this for 1.2?

We need to make sure the queue assembly version detection works in all our launchers (1.3, 2.0, androud, byodc, cloudcashbox).

**Comment by TSchmiedlechner** [comment]
@volllly Good point with the testing, added tasks for this 👍🏻 

I don't think that I would add this to 1.2, the benefit seems pretty limited to me there as anyone nobody is updating their MW 🤔 what do you think?

**Comment by volllly** [comment]
👍 I guess this will anyways need to be nullable since we don't have it for historic data so it's no problem if we don't have it for 1.2
